application: engaged-hook-806
version: 2
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /css
  static_dir: css
  expiration: "1d 0m"
- url: /js
  static_dir: js
  expiration: "1d 0m"
- url: /fonts
  static_dir: fonts
  expiration: "1d 0m"
- url: /img
  static_dir: img
  expiration: "1d 0m"
- url: /less
  static_dir: less
  expiration: "1d 0m"
- url: /blog/css
  static_dir: css
  expiration: "1d 0m"
- url: /blog/js
  static_dir: js
  expiration: "1d 0m"
- url: /blog/fonts
  static_dir: fonts
  expiration: "1d 0m"
- url: /blog/img
  static_dir: img
  expiration: "1d 0m"
- url: /blog/less
  static_dir: less
  expiration: "1d 0m"


- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
